//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.21 at 05:14:36 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vtb.com/vladislav/spring/web/services/lesson12/homework", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vtb.vladislav.spring.web.services.lesson12.homework;
